name: GitHub Actions Demo
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env: 
      DX_CLI_URL: https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
      DECRYPTION_KEY: B631F52AB46DEF247BDB89FFBC7AC276990F3D432D6C6F1AFAA11F69CB76C895
      DECRYPTION_IV: ACBE63104EE72E110CF200B34B1506F6
      HUB_CONSUMER_KEY: 3MVG9Gdzj3taRxuN9gWELaSkAKOA7BxrJMtZf_HTIb0gYwUGsrZu.ivulmqc_7xwWf2n55G5GEUUlAwXYiIT8
      JWT_KEY_FILE: assets/server.key
      SCRATCH_USER_TWO: test-sapwh63savra@example.com
    steps:
      - run: |
              echo 'sfdx cli install'
              mkdir sfdx
              wget -qO- $DX_CLI_URL | tar xJ -C sfdx --strip-components 1
              ./sfdx/install
              sfdx
              mkdir tmp
      - run: |
              echo 'make hub key'
              pwd
              cd ..
              cd ..
              pwd
              ls
              openssl enc -nosalt -aes-256-cbc -d -in assets/server.key.enc -out assets/server.key -base64 -K $DECRYPTION_KEY -iv $DECRYPTION_IV
      - run: |
              echo 'sfdx auth in cli'
              sfdx auth:jwt:grant --clientid $HUB_CONSUMER_KEY --jwtkeyfile $JWT_KEY_FILE --username $SCRATCH_USER_TWO -a hub -r https://test.salesforce.com




      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."